### ISSUE TITLE
Add default page to render when no routes match url

### ISSUE THREAD

**Issue by madeline-petersen** [smirkspace/smirkspace#50]
When an unrecognized string is entered, react-router doesn't know what to render 😞 .

We need to add a default path to load when this happens.  I believe you can do this using IndexRoute (see examples [here](https://github.com/ReactTraining/react-router/blob/master/docs/guides/IndexRoutes.md)).

You'll need to add IndexRoute to the list of things we're importing from react-router:
import { Router, Route, browserHistory, IndexRedirect, **IndexRoute**, IndexLink, Link } from 'react-router'

Here's an example of the issue:
![screen shot 2016-10-18 at 9 54 32 pm](https://cloud.githubusercontent.com/assets/9222076/19506111/7d37636a-957d-11e6-942b-078995092bff.png)

**Comment by tbakerx** [comment]
Fixed
